### ISSUE TITLE
Make sure docs are up-to-date

### ISSUE THREAD

**Issue by sobolevn** [sobolevn/git-secret#111]
Is it outdated right now?

Feel free to ask for any help.

**Comment by hurricanehrndz** [comment]
Nope, I updated the man pages and documented the new "-m" option. I update the contribution file discussing on how to run local ci tests and a note that users should do so before submitting a pull request. I didn't go into to much detail about how changes tracked on plain files using their sha256 sums, so that they are not needlessly encrypted. Do you want me to add some details somewhere documenting exactly what occurs with the "-m" option on hide?

**Comment by sobolevn** [comment]
Yes, that would be great!
