### ISSUE TITLE
Incorrect Graphic in README

### ISSUE THREAD

**Issue by alichtman** [sobolevn/git-secret#173]
https://github.com/sobolevn/git-secret#contributors says "Become a Backer" when it should say "Become a Contributor"

**Comment by sobolevn** [comment]
It should not be this way. @alichtman thanks for mentioning that.

@joshrabinowitz I think that it is OpenCollective's bug. Because all we have in our readme is `<a href="graphs/contributors"><img src="https://opencollective.com/git-secret/contributors.svg?width=890" /></a>`. Or maybe I misconfigured something in the admin panel...

BTW, we got our first backer!
