### ISSUE TITLE
Sustainability

### ISSUE THREAD

**Issue by sobolevn** [sobolevn/git-secret#284]
This is a discussion place about how to make this project sustainable for a long period of time.
Collaborators and people with experience in marketing / sustaining open-source projects are welcomed to the discussion.

I believe that every job should be fairly paid. And maintainers do a great job supporting and improving this package. Since, this project is fully open-source and does not generate profit of any kind I have decided to join several funding initiatives to help this project going.

### Open Collective

We have joined Open Collective more than one year ago. And we have managed to receive our first and only `4$` donation.

### SeedAndDew

A month ago https://www.seedanddew.com project reached me and offered their help in generating some profit. You can read more how they work on their website. TLDR: they sell subscriptions and then distribute these users' money based on project usage.

This might work I guess.

### Other ideas

Patreon? Any other platforms? I don't have any experience on this 🙂 

## Profit distribution

There is an important question of how any potential profit should be distributed.
My initial idea was:

- We should pay project maintainers first (not including myself)
- We should pay [distributions maintainers](https://aur.archlinux.org/packages/git-secret/) second
- We not keep any money for any other reasons

We also need to find all the maintained packages of `git-secret` and reach to the ones who's maintaining them.

I was not able to find this very useful website where you can find all the information about a package on different OS. So, here are some distributions that are maintained:

- https://pkgs.alpinelinux.org/package/edge/testing/x86/git-secret
- https://aur.archlinux.org/packages/git-secret/
- https://packages.ubuntu.com/bionic/git-secret
- https://packages.debian.org/sid/git-secret
- I am pretty sure that are others

## Call for discussion

What do you think about it? 
Do you see any possible ways to achieve that?

cc maintainers @joshrabinowitz @simbo1905 @hurricanehrndz

**Comment by joshrabinowitz** [comment]
Sounds fine to me, let's give it a shot. 
I like the idea of tracking, promoting, and helping keep up-to-date all the git-secret packages too.

**Comment by simbo1905** [comment]
I don't think its about the money. I think money complicates things. I think seeking to get money and then distributing it will have a negative effect. Community, shared purpose, the satisfaction of giving back, of making something useful, of building a tool that other use, is the motivation that drives opensource. 

I don't have a problem with joint license or someone making money selling services based on what I help make. Yet even then I don't want any money from them, I don't want the overhead of thinking maybe I should spend a bit less time with my children and a bit more time on a feature, because I might get more money. For that reason, I don't want shares or options or anything else that makes contribiting ”work” not ”hobby”. 

My vote is to end all money raising activities as a project. Move that activity to a company selling support that folks can join if they want to get paid, but please keep money out of the day-to-day workings of this project.

**Comment by joshrabinowitz** [comment]
Hm.

First of all, I think this is basically a moot topic because I don't think anyone is going to contribute money meaningfully to git-secret. Also, seems like the people who have put the most work into git-secret (as decided by sobolevn) should have the most say in this topic.

If there are avenues to get money to help pay for maintenance and development of git-secret, I don't think we should shut that off. It takes real effort and work to keep this project going. Conversely, I don't think anyone is going to add spurious features or code to git-secret to try to get funding from the project. 

I think it's clear that git-secret support isn't going to be a big money maker for any company (not that it should be, but income from support is probably a non-starter)

Lastly I'm fine with most (or all) of the money going to @sobolevn, and if he wants to distribute some of git-secret's income, I'm fine with him deciding informally how that works, and I'm not worried that it will effect the day-to-day workings on this project.

Again, I think this is ultimately moot because I don't think there's going to be significant money generated to write/support git-secret, but I'm loathe to shut down the exercise just on principle.

To the issue of reaching out to all the maintainers, yeah, we should do that.

**Comment by sobolevn** [comment]
Ok, so let's sum things up:

1. we should reach out to the packages maintainers
2. we should hold off this "sustainability" topic, since none of us are really interested / knowing how to do that

Let's create a separate issue about package managers.
And feel free to reopen this one if you come up with some new ideas.

Thanks for sharing your opinions! It means a lot to me!

**Comment by joshrabinowitz** [comment]
I sort of said the opposite of what you say in 2). But I defer to your decision.
