### ISSUE TITLE
Consider effect of removing 'set -e' from main.sh

### ISSUE THREAD

**Issue by joshrabinowitz** [sobolevn/git-secret#288]
In commit https://github.com/sobolevn/git-secret/commit/4a3877b4869f161abb67a36edbf0a23ec042a78b , I removed the line 

    set -e

and replaced it with the comment:

     # we don't use set -e, it messes up hide -F and reveal -F error handling 

See: https://github.com/sobolevn/git-secret/commit/4a3877b4869f161abb67a36edbf0a23ec042a78b#r31536335

I _suspect_ this may cause other issues with error handling (because bash will no longer automatically die on certain classes of failures, see https://www.gnu.org/software/bash/manual/html_node/The-Set-Builtin.html#The-Set-Builtin , which has detailed information about 'set -e')

Any thoughts / input on removing 'set -e'? 
I didn't want to make such a large change to git-secret error handling without any discussion.

**Comment by sobolevn** [comment]
I am not quite sure how does it really affect errors. Because we use `set -e` in every module, not just one of them. And during the build phase they are all glued together.

So, I am not a fan of removing it somewhere. Since:
1. We can not really tell what will happen and where
2. It will bring inconsistency to the code base
3. I am pretty sure that there are different ways / hacks / etc to nail it

What were your problems with `-F` errors?

**Comment by joshrabinowitz** [comment]
Glad I brought it up!

@sobolevn asked:
> Q: What were your problems with -F errors?

Using `set -e`  globally caused the script to stop if there was an error with gpg  (for example using expired keys with `hide -F`), and `git secret hide -F` says it will continue after such errors.  

I've rewritten the code to disable `set -e` as little as possible, but I'm not sure that's the best way to handle the issue. See https://github.com/sobolevn/git-secret/pull/287#discussion_r238439432 for more details and discussion.

**Comment by joshrabinowitz** [comment]
closing because we minimize disabling of '-e' in #287
