### ISSUE TITLE
Cannot encrypt for a certain set of keys.

### ISSUE THREAD

**Issue by hickscorp** [sobolevn/git-secret#290]
A colleague of mine has several keys. Once I `git secret tell` him, the cannot be encrypted anymore (`git secret hide` has non-zero exit) but **no error message is shown** which IMO is quite critical because it could be disregarded by a human.

I believe the failure is caused by one of the keys owned by `jean dot parpaillon at free point fr` (He authorised me to mention his address here for conducting further tests).

**Comment by joshrabinowitz** [comment]
Hello @hickscorp ,

Thanks for filing this issue. I looked into this a little more, and according to <https://pgp.surfnet.nl/pks/lookup?search=jean.parpaillon%40free.fr&fingerprint=on&op=index>) the key for that email address has been revoked.

The error checking and logging in git-secret have been improved since the release of 0.2.4.  
So the current master branch will give you better error messages if a file can't be encrypted or decrypted.

**Comment by joshrabinowitz** [comment]
If there's something I'm missing here please let me know

**Comment by hickscorp** [comment]
@joshrabinowitz Thanks for the update. Sorry, just got back home from a trip abroad.
I'm using `git-secret` version `0.2.2` as that's the package that gets installed when running `apt-get install git-secret` on Xubuntu 18.04. Ideally I'd like to stay with mainstream packages - having the binary manually installed is the best way for me to forget to update it ;)

Thanks! I'll keep checking on the `deb` packages for updates.

**Comment by joshrabinowitz** [comment]
@hickscorp we have made changes about error reporting and handling of expired, revoked, and otherwise invalid keys. 

Also you can install current versions of git-secret using deb packages at: 
https://dl.bintray.com/sobolevn/deb/
We are still working on getting git-secret updated in debian

**Comment by joshrabinowitz** [comment]
Closed by #553
