### ISSUE TITLE
"make test" is failing for `gnupg2>=2.1.0`

### ISSUE THREAD

**Issue by antmak** [sobolevn/git-secret#46]
I run "make test" and see error message "line 96: _get_gpg_fingerprint_by_email: command not found" . It prompts for passphrase on gpg key "user1@gitsecret.io" "user2@gitsecret.io"

Should I create gpg keys for user1 and user2? Could you mark about this in CONTRIBUTING.md ?

**Comment by sobolevn** [comment]
What are your os and shell?

It should not be like this. You can have a look at `travis.yml`.

**Comment by antmak** [comment]
{Fedora 24, Fedora 21} x86_64. bash, version 4.3.42(1)-release (x86_64-redhat-linux-gnu). gpg2.

**Comment by sobolevn** [comment]
Ok, I will have a look at it soon.

**Comment by antmak** [comment]
Thx. I'll try also

**Comment by sobolevn** [comment]
@antmak sorry it took me so long to fix this issue.

I did a lot of research for this case. Here's what I came up with: only `install_fixture_full_key` is affected (so, only tests), because there's a breaking change in the `gnupg2` since versions `2.1.x`. Everything works just fine with the versions `2.0.x`: https://travis-ci.org/sobolevn/git-secret/jobs/164323199#L253

What kind of changes there are? Some kind of `--export-secret-key` magic. 

This command works in the shell: 

> [root@bc3d887d95d3 git-secret]# gpg2 --homedir="tests/fixtures/gpg/user1" --no-permission-warning --output "private_key.key" --batch --yes --armor --pinentry-mode=loopback --passphrase="user1pass" --no-tty --export-secret-key "user1@gitsecret.io"

The same command fails when running tests:

> (in test file /code/git-secret/tests/test_changes.bats, line 37)
>      `[ "$status" -eq 0 ]' failed
>    gpg: /code/git-secret/temp/trustdb.gpg: trustdb created
>    gpg: key D2805A4182E99FF4: public key "user1 <user1@gitsecret.io>" imported
>    gpg: key D2805A4182E99FF4/D2805A4182E99FF4: error sending to agent: No such file or directory
>    gpg: error building skey array: No such file or directory
>    gpg: Total number processed: 3
>    gpg:               imported: 1
>    gpg:       secret keys read: 3
>    gpg: DBG: FIXME: merging secret key blocks is not anymore available
>    gpg: DBG: FIXME: No way to print secret key packets here
>    gpg: key D2805A4182E99FF4: "user1 <user1@gitsecret.io>" not changed
>    gpg: Total number processed: 1
>    gpg:              unchanged: 1

I have found several issues on the internet with the same problems: 
1. https://github.com/keybase/keybase-issues/issues/1712
2. https://bugzilla.redhat.com/show_bug.cgi?id=841588

For now - I don't know how to fix this. I guess I have to `gpg` developers for help.
