### ISSUE TITLE
adding files from folder 

### ISSUE THREAD

**Issue by vladimir4862** [sobolevn/git-secret#50]
## What are the steps to reproduce this issue?

git secret  add folder/test.json
## What happens?

these files are not ignored are: folder/test.json ; abort.

but they are in .gitignore, there definitely is a line
folder/test.json
## Any logs, error output, etc?

these files are not ignored are: folder/test.json ; abort.
## What versions of software are you using?

**Operating system:** Ubuntu 14.04

**`git-secret` version:**  0.2.1

**Shell type and version:** bash

**Comment by vladimir4862** [comment]
maybe need to add "--no-index" in this line 
https://github.com/sobolevn/git-secret/blob/master/src/_utils/_git_secret_tools.sh#L131

**Comment by sobolevn** [comment]
Thanks! Will test it shortly.

**Comment by sobolevn** [comment]
I can not reproduce your error, this is my configuration: https://hub.docker.com/r/sobolevn/git-secret/~/dockerfile/

Steps:

> root@69f6ab52c871:/code/test# /code/git-secret/git-secret add -i sub/text.txt
> these files are not ignored: sub/text.txt ;
> auto adding them to .gitignore
> 1 items added.

Moreover, I have created a test for this error, and it works on both mac and ubuntu. See commit: https://github.com/sobolevn/git-secret/blob/904ce02cfca3e486ad588402629ded5417c6f221/tests/test_add.bats#L62

If you still suffering this error, could you please create a repo to reproduce it?

**Comment by vladimir4862** [comment]
yes with key '-i' it works 
but without this key not working 

>  vagrant@default-ubuntu-1404:~/test-secret$ cat .gitignore
>  sub/test.txt
>  vagrant@default-ubuntu-1404:~/test-secret$ git secret add sub/test.txt
>  these files are not ignored: sub/test.txt ; abort.
>  vagrant@default-ubuntu-1404:~/test-secret$ git check-ignore sub/test.txt
>  vagrant@default-ubuntu-1404:~/test-secret$ git check-ignore sub/test.txt --no-index
>  sub/test.txt
>  vagrant@default-ubuntu-1404:~/test-secret$ git secret add -i sub/test.txt
>  these files are not ignored: sub/test.txt ; 
>  auto adding them to .gitignore
>  1 items added
> vagrant@default-ubuntu-1404:~/test-secret$ cat .gitignore 
> sub/test.txt
> sub/test.txt

Could you please check it
I did not create the repository. but if it is still necessary, I can do it

git version 1.9.1

**Comment by sobolevn** [comment]
Can you try the latest version from the `develop` branch, please?

**Comment by vladimir4862** [comment]
ok, it's work for me.
thank you very much !

**Comment by sobolevn** [comment]
I will release a new version after I will fix these issues: https://github.com/sobolevn/git-secret/milestone/3

**Comment by aymens** [comment]
Happened to me! And I think I figured out the reason: 
the file I was adding is one that's already tracked, clear, and I wanted to encrypt afterwards.

**git-secret** as it is written now, knows only handle **_untracked_** files.

![git-secret](https://user-images.githubusercontent.com/631791/34568340-c2bfc66c-f165-11e7-90ed-8306bdb9103d.PNG)

1st 3 lines are echo message I've added to the git-secret script. That shows clearly that **__git_normaloze_filename_** function returns nothing.

Looking at code, @sobolevn is doing a **_git ls-files -o_**. 
Which means:

> -o
> --others
> Show other (i.e. untracked) files in the output

So if you decide to encrypt an already tracked file (that is clear obviously), you should remove it from index first:

![git-secret](https://user-images.githubusercontent.com/631791/34569313-adafaf8c-f168-11e7-952f-aaa3d5370ebc.PNG)

At that moment it would appear in the **_git ls-files -o_** results:

![git-secret](https://user-images.githubusercontent.com/631791/34569387-ea042a12-f168-11e7-9570-626eac8b3e3b.PNG)

Then **_git secret add_** it:
![git-secret](https://user-images.githubusercontent.com/631791/34569482-317c42bc-f169-11e7-9629-c925a5f35c8a.PNG)

So I think that, if handling only untracked files is a choice of the implementor, git-secret could at least warn the user that the file he's trying to encrypt should be untracked instead of an absurd message telling that the file is not a file. i.e. when git ls-files returns nothing while the file exists -> warn user.

Or git-secret should handle that transparently, i.e untracks the file before adding it if the file is already tracked.

...

**Comment by sobolevn** [comment]
Hm, we should 100% improve this. Could you please create a new issue? 
Thanks!

**Comment by aymens** [comment]
Sure I'll do it today. 
Thank you!
