### ISSUE TITLE
Skip invalid keys in keyring in 'tell'

### ISSUE THREAD

**Issue by joshrabinowitz** [sobolevn/git-secret#508]
https://github.com/sobolevn/git-secret/issues/491#issuecomment-505492667 and #492 relate to gnupg [validity values](https://github.com/gpg/gnupg/blob/master/doc/DETAILS#field-2---validity).

~We currently skip any 'revoked' keys (see #492) but there are other cases of keys we should probably skip like 'disabled', 'expired', and 'disabled' keys.~ Edit: We no longer skip revoked keys in git-secret

**Comment by joshrabinowitz** [comment]
We should also add tests for other invalid keys we skip (like #510, but for other invalid key types)

**Comment by joshrabinowitz** [comment]
On second thought: If we want git-secret to detect invalid keys, there are several cases of invalid keys, and since gnupg is not particularly helpful in reporting problems with keys, we should probably perform error reporting about why we don't use particular invalid keys.

**Comment by joshrabinowitz** [comment]
See also #238 regarding 'expired' keys

**Comment by joshrabinowitz** [comment]
@sobolevn @simbo1905 thoughts on the issue of having git-secret detect and report on unusable keys?

**Comment by simbo1905** [comment]
I agree that #516 seems the right direction.

**Comment by joshrabinowitz** [comment]
Closed as 'wontfix'

**Comment by joshrabinowitz** [comment]
Reopening, this will resolve #552

**Comment by joshrabinowitz** [comment]
@sobolevn / @simbo1905 , in light of the above comment, I'm planning fix this issue instead of closing as 'wontfix'.

**Comment by joshrabinowitz** [comment]
Closed by #553 , which issues a warning for expired/revoked/invalid keys

**Comment by sowbug** [comment]
Commenting on this closed issue because the behavior seems to be covered by the original issue description.

I'm unable to `git secret tell` an email address with two keys, one of which is disabled. I'm running 0.5.0. Is this expected?

If I `gpg --edit-key` for the disabled key, underneath the primary key it says `*** This key has been disabled`, which according to the gpg manual means "A disabled key cannot normally be used for encryption."

Yet when I `git secret tell` the email address, the response is `git-secret: abort: 2 keys found in gpg user keyring for: [address]`. While that's true, it seems intuitively that git-secret should ignore disabled keys.

Am I misunderstanding the behavior?

Note that I don't want to delete the second key, as it's still used for decryption of old files. It hasn't been revoked, and it isn't expired, either.
