### ISSUE TITLE
Can't encrypt file if one of the keys doesn't have an email and has whitespace in its comment

### ISSUE THREAD

**Issue by lufte** [sobolevn/git-secret#527]
What are the steps to reproduce this issue?
-------------------------------------------
1. Init a new git secret repo with secrets and people in it.
2. Create a gpg key with a name, no email, and a comment with whitespace in it.
3. `git secret tell` that gpg key.
4. Run `git secret hide`

What happens?
-------------
The following error is returned: `git-secret: abort: problem encrypting file with gpg: exit code 2: ...`. Also if you run `git secret whoknows`, you will see that the comment of the new gpg key spans multiple lines (mine also had a colon in it, and it was badly displayed, like an encoding issue).

What were you expecting to happen?
----------------------------------
The secrets should be encrypted using the new key as part of the group.

What versions of software are you using?
----------------------------------------
**Operating system:** (`uname -a`)
Darwin 18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64
**`git-secret` path:** (`which git-secret`) 
/usr/local/bin/git-secret
**`git-secret` version:** (`git secret --version`) …
0.2.6
**`git` version:** (`git --version`) …
git version 2.20.1
**Shell type and version:** (`$SHELL --version`) …
GNU bash, version 5.0.2(1)-release (x86_64-apple-darwin18.2.0)
**`gpg` version:** (`gpg --version`) …
gpg (GnuPG) 2.2.17

**Comment by joshrabinowitz** [comment]
Hello @lufte , and thank you for filing this issue.

git-secret currently only supports identifying keys by email address. (See issues #268, #176, #512 and PRs #243, #267 ) Since gpg key 'human names' are not intended to be unique, we don't want to add support for matching keys using them. 

The docs could use some clarification on this topic. (Filed as #529)

We do have plans to support specifying keys by fingerprints and/or key ids instead of by email: See #512 

I've opened an issue regarding git-secret's error reporting when using such keys. (Filed as #530)  

For all the reasons above, I'm closing this issue as 'wontfix'. Please let us know if you have any more comments or feedback and thank you again.
