### ISSUE TITLE
Backward compatibility 0.2.1 - 0.2.6

### ISSUE THREAD

**Issue by rjcoelho** [sobolevn/git-secret#536]
Hi,

This is what i get when trying reveal files using 0.2.1 that were hidden using 0.2.6
`
config/overlays/local/keys.config:d2f1286fad60a1c84dbe0388637f7733c9454d52bcbea8afd46ad2401a5849d2.secret: No such file or directory
`

Basically mappings how has sha1, which 0.2.1 doesn't understand. This should be an opt-in on 0.2.6 and later.

**Comment by joshrabinowitz** [comment]
@rjcoelho , I read the code too quickly. You are correct, after encryption, a hash is always written to the `mapping.cfg` file in recent versions of git-secret.  

As mentioned above, by my reading of 'semver', it's not technically a bug that persistent files from new versions of git-secret are not backward compatible with older versions of git-secret. 

Can you upgrade git-secret from 0.2.1 in your appropriate environment?

We _could_ add some sort of flag to stop writing checksums to the mappings.cfg file, but I'm reticent to add a flag just relating to the checksum in mapping.cfg.

**Comment by joshrabinowitz** [comment]
I've add a PR altering CHANGELOG.md to note the backward incompatibility. (See #537) 

Since this is the first time this has come up (and since the change was made some two years ago) I'm not planning on adding any more docs or code changes related to this topic for now. If you're ok with this resolution, feel free to close this issue, @rjcoelho ; alternately let us know below! Thanks again.
