### ISSUE TITLE
git secret add fails with file not found

### ISSUE THREAD

**Issue by rymurr** [sobolevn/git-secret#593]
What are the steps to reproduce this issue?
-------------------------------------------
1. `git secret add <filename>` on an existing repository. My key is the only key and I am the only committer

What happens?
-------------
`git-secret: abort: file not found: <filename>`

What were you expecting to happen?
----------------------------------
file to be added correctly

Any logs, error output, etc?
----------------------------
just whats is above

Any other comments?
-------------------
`git secret hide` & `git secret reveal` both work. I am using a yubikey to store my key

What versions of software are you using?
----------------------------------------
**Operating system:** (`uname -a`) Linux xxx 4.15.0-96-generic #97-Ubuntu SMP Wed Apr 1 03:25:46 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**`git-secret` path:** (`which git-secret`) /usr/bin/git-secret

**`git-secret` version:** (`git secret --version`) 0.3.1

**`git` version:** (`git --version`) 2.24.0

**Shell type and version:** (`$SHELL --version`) zsh 5.4.2 (x86_64-ubuntu-linux-gnu)

**`gpg` version:** (`gpg --version`) 2.2.4

**Comment by joshrabinowitz** [comment]
Hello, @rymurr 
I cannot replicate this issue with `git-secret version 0.3.2` (the current version. I would also be surprised if I could replicate this in 0.3.1)

If you are still having the problem, please provide detailed steps for us to replicate the issue on our machines.

Here's the steps I tried to replicate your issue. 

````
mkdir git-secret-test
cd git-secret-test
git init
git secret init
git tell myuser@example.com
echo contents > file1.txt
git secret add file1.txt
git secret hide
echo contents2 > file2.txt
git secret add file2.txt
git secret hide
````

**Comment by rymurr** [comment]
Thanks @joshrabinowitz 

I am also perplexed as it seems a strange issue. What is the process behind the scenes to add a secret? I am trying to figure out if there is something with the yubikey that it doesn't like?

I also confirmed that adding a secret from the root of the git directory works. It only fails when adding a secret from a sub-directory. Is there anything special about a sub-directory that git-secrets wouldn't like?

**Comment by joshrabinowitz** [comment]
I just checked out the code for v0.3.1 , created a subdir of my git-secret repo, cd'ed into it, created a file there, and using v0.3.1, successfully run `add` and `hide` on the file. So I'm still unable to replicate.

>What is the process behind the scenes to add a secret? I am trying to figure out if there is something with the yubikey that it doesn't like?

You can see the code that `git secret add` uses 
at (https://github.com/sobolevn/git-secret/blob/master/src/commands/git_secret_add.sh) 
and (https://github.com/sobolevn/git-secret/blob/master/src/_utils/_git_secret_tools.sh) 

The tests for operating in subdirectories are pretty thorough, but there is no automated testing around yubikeys; it is possible this issue is related to the yubikey.

* Can you try with v0.3.2 (or better yet, the version of git-secret in the `master` branch of the repo)? Then, if this is related to gnupg, we may see error messages emitted.

* Also, if you could please provide complete steps to replicate your issue, it might show some hint into the problem.

**Comment by joshrabinowitz** [comment]
@rymurr See also the `bash -x` debugging technique described in #594

**Comment by rymurr** [comment]
hey @joshrabinowitz that did the trick. It was a file that had been downloaded from a website and had a hidden unicode character in the name replacing –  with - fixed the problem. Thanks for the help!
