### ISSUE TITLE
git-secret: abort: cannot find decrypted version of file:

### ISSUE THREAD

**Issue by kuvaldini** [sobolevn/git-secret#672]
What are the steps to reproduce this issue?
-------------------------------------------
1. init, tell, hide, add, commit, push      on Mac with git-secret 0.4.0, gpg (GnuPG) 2.2.19 libgcrypt 1.8.5
2. clone, gpg --import, git-secret reveal on ubuntu:latest in docker with git-secret 0.4.0, gpg (GnuPG) 2.3.1, libgcrypt 1.9.3

What happens?
-------------
```
git secret reveal
git-secret: abort: cannot find decrypted version of file: .github/dockerhub.env
```

What were you expecting to happen?
----------------------------------
reveal

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.)

**Comment by sobolevn** [comment]
@kuvaldini thanks. 

Looks like this condition does not work for you: https://github.com/sobolevn/git-secret/blob/master/src/commands/git_secret_reveal.sh#L68

Some questions:
1. Are you sure that `.git` and `.gitsecret` folders are inside the container?
2. Are you sure that encrypted files are there as well?

**Comment by sobolevn** [comment]
Is your docker filesystem writtable?
What happens when you try `reveal -F`?

**Comment by sobolevn** [comment]
@kuvaldini can you please submit a reproducable `Dockerfile` example?

**Comment by kuvaldini** [comment]
I think i know what happened - i told about the secret after if was added and hidden.
```
git secret init
git secret tell -m
git secret add file.txt
git secret hide
git add && git commit && git push
git secret tell ci@mail.com
git secret hide #does nothing?
git add && git commit && git push
git add && git commit && git push
```
In docker 
```
gpg --import <pri-key-for-ci-mail-com
git clone
git secret reveal
ERRROR
```

I just reinitialized git-secret but this time I `git-secret-tell` before adding a secret. And all works fine.

**Comment by sobolevn** [comment]
Good that it is solved now! 👍

**Comment by kuvaldini** [comment]
But error message still is not obvious, even for its author ;)

**Comment by dudulasry** [comment]
Did you manage to find a solution? I'm also experiencing this problem.

**Comment by joshrabinowitz** [comment]
I looked into this briefly, and I think the cause of the confusing error message is that we don't check for the  encrypted version of the file before trying to `reveal` it, because normally if gpg has an issue decrypting a file it will yield an error message. 

However, it looks like if you try to decrypt a non-existing file, that's not considered an error by gpg.

I think the solution to this is to add a check to the `_decrypt` function in `src/_utils/_git_secret_tools.sh` to give an error if the _encrypted_ version of the file cannot be found.  Perhaps it could even look at the files listed in `mapping.cfg` and let you know if you'd never `add`ed that file (which would yield a more informative error message).
