### ISSUE TITLE
gpg: cannot open '/dev/tty': No such device or address

### ISSUE THREAD

**Issue by cycloss** [sobolevn/git-secret#863]
I'm attempting to use git-secret within a github action, but I'm getting the error:

```
gpg: cannot open '/dev/tty': No such device or address
```

The command i'm using in the action is:

```
Run git secret reveal -p "$GIT_SECRET_PASS" 
```

What's strange is that I've had this working in the past, but i've not encountered the error. I tried to use `-f`, but that doesn't help. Any ideas as to why I might be getting this error?

**Comment by joshrabinowitz** [comment]
I'm pretty sure this means that gpg is trying to get user input from the terminal but is unable (because it's being run in a git action).

Can you put git-secret into verbose mode by setting SECRETS_VERBOSE=1 in your environment variables (or pass -v to each git-secret command) and re-posting the results?

**Comment by joshrabinowitz** [comment]
you don't say which version of git-secret you're using; if you can try with the latest `master` branch you may get better error messaging too

**Comment by cycloss** [comment]
@joshrabinowitz apologies. Completely my fault. I was referencing the wrong environment variable and so I guess `tty` was being opened as `gpg` was asking for the password to be re-entered.
